services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - ecommerce-network
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  
  nginx:
    image: nginx:latest
    container_name: ecommerce-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ecommerce-network

  db:
    image: mariadb:10.5
    container_name: ecommerce-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_DATABASE: ecommerce
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  db-data:
